---
name: James T. Durant
position: "Senior Industrial Hygienist"
address: "HETI"
phone: +1 404.632.1529
email: "jdurant@hetiservices.com"
github: YoJimboDurant
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am an industrial hygienist and environmental scientist specializing in air dispersion modeling, environmental risk assessment, and applied data science. My work focuses on analyzing complex environmental exposures, translating technical findings into actionable insights, and supporting decision-making in regulatory, public health, and insurance contexts."
header-includes: \photo[rectangle,edge,left]{../jim1.jpeg}
output: vitae::awesomecv
---


\raggedright


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(glue)
library(tidyverse)
mycvdata <- read_rds("../mycvdata.rds")
```



# Publications
```{r publications}
detailed_entries(
  mycvdata$pubsx,
  with  = what,
  where = with,
  what = glue::glue("{where} , {when}")
)

```

# Presentations

```{r presies}

detailed_entries(
  mycvdata$presx,
  with  = what,
  where = with,
  what = glue::glue("{where} , {when}")
 
)
```

# US Government Publications

```{r USG}
detailed_entries(
mycvdata$govtx,
  with  = what,
  where = with,
   what = glue::glue("{where} , {when}")
)
```




# Employment
```{r employment}
mycvdata$empx

```


# Education

```{r education}
# mycvdata$edux$what[[1]] <- glue(mycvdata$edux$what[[1]], " Industrial Hygiene")
# mycvdata$edux$what[[2]] <- glue(mycvdata$edux$what[[2]], " Environmental Health Science")
cls <- class(mycvdata$edux)
mycvdata$edux$what[[1]] <- "M.S.P.H. Industrial Hygiene"
mycvdata$edux$what[[2]] <- "B.S.E.H. Environmental Health Science"
class(mycvdata$edux) <- cls
mycvdata$edux
```

# Certifications

```{r, echo = FALSE}
mycvdata$certs
```


# Continuing Education
```{r coned}
mycvdata$coned <- mycvdata$coned |>rename(with = what, what = with)
mycvdata$coned
```


# Hobbies/Interests

 * Hiking, amateur radio (FCC Amateur Extra Radio License KE4MKG)

