---
name: James T. Durant
position: "Environmental Health Scientist"
address: "840 Ashland Park Way, Lawrenceville GA"
phone: +1 770.488.0668
email: jamesdrenda@charter.net
github: YoJimboDurant
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am interested in air dispersion modeling, risk assessment, and environmental statistics. I currently am the acting branch associate director for science for the western branch of ATSDR's Division of Communinity Health Investigations."
profilepic: ../jim.jpeg
output: vitae::moderncv
---


\raggedright


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(glue)
library(tidyverse)
mycvdata <- read_rds("../mycvdata.rds")
```



# Publications
```{r publications}
mycvdata$pubsx

```

# Presentations

```{r presies}
mycvdata$presx
```

#Employment
```{r employment}
mycvdata$empx

```


# Education

```{r education}
mycvdata$edux
```



# Hobbies/Interests

 * Hiking, jogging, ameuteur radio, and ballroom dancing

\fart
