---
name: James T. Durant
position: "Environmental Health Scientist"
address: "Agency for Toxic Substances and Disease Registry"
phone: +1 770.488.0668
profilepic: ../jim.jpeg
email: "hzd3@cdc.gov"
github: YoJimboDurant
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I am interested in air dispersion modeling, risk assessment, and environmental statistics. I currently am the acting branch associate director for science for the western branch of ATSDR's Division of Communinity Health Investigations."
header-includes: \skills{{Industrial Hygiene/4.5},{Statistics/3},{Risk Assessment/2},{R/3},{Toxicology/2},{Air Dispersion Modeling/2}}
output: vitae::twentyseconds
---


\raggedright


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(glue)
library(tidyverse)
mycvdata <- read_rds("../mycvdata.rds")
```


#Employment
```{r employment}
mycvdata$empx

```

# Education

```{r education}
mycvdata$edux
```

# Publications
```{r publications}
mycvdata$pubsx

```

\endfirstpage

# Presentations

```{r presies}
mycvdata$presx
```


# Hobbies/Interests

 * Hiking, jogging, ameuteur radio, and ballroom dancing

