---
name: James T. Durant
position: "Senior Industrial Hygienist"
address: "Lawrenceville, Georgia"
phone: +1 404.632.1529
email: "jdurant@hetiservices.com"
github: YoJimboDurant
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Senior industrial hygienist with expertise in air dispersion modeling, exposure assessment, environmental risk analysis, and applied data science. Experienced in translating complex technical findings for regulatory, public health, insurance, and litigation contexts."
profilepic: ./jim.jpeg
output: vitae::hyndman
header-includes:
  - |
    \makeatletter

    \renewcommand{\section}{\@startsection{section}{1}{\z@}%
      {-1.6ex \@plus -.5ex \@minus -.2ex}%
      {1.0ex \@plus .2ex}%
      {\normalfont\LARGE\bfseries}}

    \renewcommand{\subsection}{\@startsection{subsection}{2}{\z@}%
      {-1.2ex \@plus -.5ex \@minus -.2ex}%
      {0.8ex \@plus .2ex}%
      {\normalfont\large\bfseries}}

    \makeatother

    \setlength{\parskip}{0.45em}
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(glue)
library(tidyverse)
mycvdata <- read_rds("../mycvdata.rds")
```



# Publications
```{r publications}
mycvdata$pubsx

```


# Government Publications

```{r USG}
mycvdata$govtx
```




# Presentations

```{r presies}
mycvdata$presx
```


# Employment
```{r employment}
mycvdata$empx

```


# Education

```{r education}
# mycvdata$edux$what[[1]] <- glue(mycvdata$edux$what[[1]], " Industrial Hygiene")
# mycvdata$edux$what[[2]] <- glue(mycvdata$edux$what[[2]], " Environmental Health Science")
cls <- class(mycvdata$edux)
mycvdata$edux$what[[1]] <- "M.S.P.H. Industrial Hygiene"
mycvdata$edux$what[[2]] <- "B.S.E.H. Environmental Health Science"
class(mycvdata$edux) <- cls
mycvdata$edux
```

# Certifications

```{r, echo = FALSE}
mycvdata$certs
```



# Continuing Education
```{r coned}
mycvdata$coned
```


# Hobbies/Interests

 * Hiking, amateur radio (FCC Amateur Extra Radio License KE4MKG)

